name: Build

on:
  push:
    branches:
      - main
      - release/*
    tags:
      - "v*"
  pull_request:
    branches:
      - main
      - release/*
    types: [ labeled, opened, synchronize, reopened ]
jobs:
  # Prime a single LFS cache and expose the exact key for the matrix
  WarmLFS:
    runs-on: ubuntu-latest
    outputs:
      lfs_key: ${{ steps.expose-key.outputs.lfs_key }}
    steps:
      - name: Git Config
        shell: bash
        run: |
          git config --global core.autocrlf false
          git config --global core.longpaths true

      - name: Git Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      # Deterministic list of LFS object IDs, then compute a portable key:
      # - `git lfs ls-files -l` lists all tracked LFS objects with their SHA-256
      # - `awk '{print $1}'` extracts just the SHA field
      # - `sort` sorts in byte order (hex hashes sort the same everywhere)
      # This ensures the file content is identical regardless of OS or locale
      - name: Git Create LFS id list
        shell: bash
        run: git lfs ls-files -l | awk '{print $1}' | sort > .lfs-assets-id

      - name: Git Expose LFS cache key
        id: expose-key
        shell: bash
        env:
          LFS_KEY: lfs-${{ hashFiles('.lfs-assets-id') }}-v1
        run: echo "lfs_key=$LFS_KEY" >> "$GITHUB_OUTPUT"

      - name: Git Setup LFS Cache
        uses: actions/cache@v4
        with:
          path: .git/lfs
          key: ${{ steps.expose-key.outputs.lfs_key }}

      - name: Git Pull LFS
        shell: bash
        run: git lfs pull
  
  Build:
    needs: WarmLFS
    strategy:
      matrix:
        options:
          - os: ubuntu-latest
            framework: net9.0
            sdk: 9.0.x
            sdk-preview: true
            runtime: -x64
            codecov: false
          - os: macos-latest
            framework: net9.0
            sdk: 9.0.x
            sdk-preview: true
            runtime: -x64
            codecov: false
          - os: windows-latest
            framework: net9.0
            sdk: 9.0.x
            sdk-preview: true
            runtime: -x64
            codecov: false

          - os: ubuntu-latest
            framework: net8.0
            sdk: 8.0.x
            runtime: -x64
            codecov: false
          - os: macos-latest
            framework: net8.0
            sdk: 8.0.x
            runtime: -x64
            codecov: false
          - os: windows-latest
            framework: net8.0
            sdk: 8.0.x
            runtime: -x64
            codecov: false

    runs-on: ${{matrix.options.os}}

    steps:
      - name: Git Config
        shell: bash
        run: |
          git config --global core.autocrlf false
          git config --global core.longpaths true

      - name: Git Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      # Use the warmed key from WarmLFS. Do not recompute or recreate .lfs-assets-id here.
      - name: Git Setup LFS Cache
        uses: actions/cache@v4
        with:
          path: .git/lfs
          key: ${{ needs.WarmLFS.outputs.lfs_key }}

      - name: Git Pull LFS
        run: git lfs pull

      - name: NuGet Install
        uses: NuGet/setup-nuget@v2

      - name: NuGet Setup Cache
        uses: actions/cache@v4
        id: nuget-cache
        with:
          path: ~/.nuget
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj', '**/*.props', '**/*.targets') }}
          restore-keys: ${{ runner.os }}-nuget-

      - name: DotNet Setup
        if: ${{ matrix.options.sdk-preview != true }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x

      - name: DotNet Setup Preview
        if: ${{ matrix.options.sdk-preview == true }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            9.0.x

      - name: DotNet Build
        if: ${{ matrix.options.sdk-preview != true }}
        shell: pwsh
        run: ./ci-build.ps1 "${{matrix.options.framework}}"
        env:
          SIXLABORS_TESTING: True

      - name: DotNet Build Preview
        if: ${{ matrix.options.sdk-preview == true }}
        shell: pwsh
        run: ./ci-build.ps1 "${{matrix.options.framework}}"
        env:
          SIXLABORS_TESTING_PREVIEW: True

      - name: DotNet Test
        if: ${{ matrix.options.sdk-preview != true }}
        shell: pwsh
        run: ./ci-test.ps1 "${{matrix.options.os}}" "${{matrix.options.framework}}" "${{matrix.options.runtime}}" "${{matrix.options.codecov}}"
        env:
          SIXLABORS_TESTING: True
          XUNIT_PATH: .\tests\PolygonClipper.Tests # Required for xunit

      - name: DotNet Test Preview
        if: ${{ matrix.options.sdk-preview == true }}
        shell: pwsh
        run: ./ci-test.ps1 "${{matrix.options.os}}" "${{matrix.options.framework}}" "${{matrix.options.runtime}}" "${{matrix.options.codecov}}"
        env:
          SIXLABORS_TESTING_PREVIEW: True
          XUNIT_PATH: .\tests\PolygonClipper.Tests # Required for xunit

  Publish:
    needs: [Build]

    runs-on: ubuntu-latest

    if: (github.event_name == 'push')

    steps:
      - name: Git Config
        shell: bash
        run: |
          git config --global core.autocrlf false
          git config --global core.longpaths true

      - name: Git Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: NuGet Install
        uses: NuGet/setup-nuget@v2

      - name: NuGet Setup Cache
        uses: actions/cache@v4
        id: nuget-cache
        with:
          path: ~/.nuget
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj', '**/*.props', '**/*.targets') }}
          restore-keys: ${{ runner.os }}-nuget-

      - name: DotNet Pack
        shell: pwsh
        run: ./ci-pack.ps1

      - name: Feedz Publish
        shell: pwsh
        run: |
          dotnet nuget push .\artifacts\*.nupkg -k ${{secrets.FEEDZ_TOKEN}} -s https://f.feedz.io/sixlabors/sixlabors/nuget/index.json --skip-duplicate
          dotnet nuget push .\artifacts\*.snupkg -k ${{secrets.FEEDZ_TOKEN}} -s https://f.feedz.io/sixlabors/sixlabors/symbols --skip-duplicate

      - name: NuGet Publish
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        shell: pwsh
        run: |
          dotnet nuget push .\artifacts\*.nupkg -k ${{secrets.NUGET_TOKEN}} -s https://api.nuget.org/v3/index.json --skip-duplicate
          dotnet nuget push .\artifacts\*.snupkg -k ${{secrets.NUGET_TOKEN}} -s https://api.nuget.org/v3/index.json --skip-duplicate
